plugin: hetzner.hcloud.hcloud
api_token: "GVcFJOaB08HIrGqaWluslBY6JhxlTP9G6C2gOM0S8u6eOGLLdaRLXeFJA2Pn0Rva"
status:
  - running
keyed_groups:
  - key: hcloud_location
    prefix: hcloud_location
  - key: image_os_flavor
    separator: ""
  - key: hcloud_status
    prefix: server_status
  - key: hcloud_labels
