- name: remove all servers
  hosts: localhost
  connection: local
  gather_facts: False
  user: root
  vars:
    hcloud_token: "GVcFJOaB08HIrGqaWluslBY6JhxlTP9G6C2gOM0S8u6eOGLLdaRLXeFJA2Pn0Rva"
  tasks:
    - name: remove all clients
      loop: "{{ groups['clients'] }}"
      hcloud_server:
        api_token: "{{ hcloud_token }}"
        name: "{{ item }}"
        state: absent
    - name: remove all nodes
      loop: "{{ groups['nodes'] }}"
      hcloud_server:
        api_token: "{{ hcloud_token }}"
        name: "{{ item }}"
        state: absent
