HOST_1 := "sin"
HOST_2 := "hel"
HOST_3 := "ash"

BIN_PATH := "bin/probench/bin/probench"
export BENCH_RESULTS_DIR := "benchmark-results"

package-bin:
    fish scripts/create-bin.fish

prdt-benchmark-local iterations warmup measurement op="write" mode="timed" kv_range="10000 20000" block_size="2000":
	#!/usr/bin/env fish
	set fish_trace 1

	set -lx ID (random)

	set -lx SYSTEM_ID prdt

	for i in (seq {{iterations}});
		set -lx RUN_ID cluster3-{{op}}-{{mode}}-{{warmup}}_{{measurement}}-id{$ID}_run$i

		echo Iteration $i
		echo RUN_ID $RUN_ID

		# start cluster
		{{BIN_PATH}} node --name NODE1 --listen-client-port 8010 --listen-peer-port 8011 --cluster --initial-cluster-ids NODE1 NODE2 NODE3 &
		set -l NODE1 (jobs -pl)

		{{BIN_PATH}} node --name NODE2 --listen-client-port 8020 --listen-peer-port 8021 --cluster localhost:8011 --initial-cluster-ids NODE1 NODE2 NODE3 &
		set -l NODE2 (jobs -pl)

		{{BIN_PATH}} node --name NODE3 --listen-client-port 8030 --listen-peer-port 8031 --cluster localhost:8011 localhost:8021 --initial-cluster-ids NODE1 NODE2 NODE3 &
		set -l NODE3 (jobs -pl)
		sleep 5

		# start client
		just start-pb-bench-client {{warmup}} {{measurement}} localhost {{op}} {{mode}} "{{kv_range}}" {{block_size}}
		kill $NODE1 $NODE2 $NODE3
		sleep 10
	end

etcd-benchmark-local iterations warmup measurement op="write" mode="timed" kv_range="10000 20000" block_size="2000" leader="8010":
	#!/usr/bin/env fish
	set fish_trace 1

	set -lx ID (random)

	set -lx SYSTEM_ID etcd

	for i in (seq {{iterations}});
		set -lx RUN_ID cluster3-{{op}}-{{mode}}-{{warmup}}_{{measurement}}-id{$ID}_run$i

		echo Iteration $i
		echo RUN_ID $RUN_ID

		# start etcd cluster
		set -lx TOKEN token-01
		set -lx CLUSTER_STATE new
		set -lx NAME_1 machine-1
		set -lx NAME_2 machine-2
		set -lx NAME_3 machine-3
		set -lx HOST_1 localhost
		set -lx HOST_2 localhost
		set -lx HOST_3 localhost
		set -lx CLUSTER {$NAME_1}=http://{$HOST_1}:2381,{$NAME_2}=http://{$HOST_2}:2382,{$NAME_3}=http://{$HOST_3}:2383

		rm -rf /tmp/data*.etcd

		etcd --data-dir=/tmp/data1.etcd --name {$NAME_1} --initial-advertise-peer-urls http://localhost:2381 --listen-peer-urls http://localhost:2381 --advertise-client-urls http://localhost:8010 --listen-client-urls http://localhost:8010 --initial-cluster {$CLUSTER} --initial-cluster-state {$CLUSTER_STATE} --initial-cluster-token token-01 &
		set -l NODE1 (jobs -pl)

		etcd --data-dir=/tmp/data2.etcd --name {$NAME_2} --initial-advertise-peer-urls http://localhost:2382 --listen-peer-urls http://localhost:2382 --advertise-client-urls http://localhost:8020 --listen-client-urls http://localhost:8020 --initial-cluster {$CLUSTER} --initial-cluster-state {$CLUSTER_STATE} --initial-cluster-token token-01 &
		set -l NODE2 (jobs -pl)

		etcd --data-dir=/tmp/data3.etcd --name {$NAME_3} --initial-advertise-peer-urls http://localhost:2383 --listen-peer-urls http://localhost:2383 --advertise-client-urls http://localhost:8030 --listen-client-urls http://localhost:8030 --initial-cluster {$CLUSTER} --initial-cluster-state {$CLUSTER_STATE} --initial-cluster-token token-01 &
		set -l NODE3 (jobs -pl)

		sleep 5

		set -lx ETCD_CLUSTER "$HOST_1:8010,$HOST_2:8020,$HOST_3:8030"

		# move leader to specified node
		set -lx leader {{leader}}	
		set -lx ep_status (string split "," (etcdctl --endpoints $ETCD_CLUSTER endpoint status | grep {$leader}))
		etcdctl --endpoints $ETCD_CLUSTER move-leader (string trim $ep_status[2])

		sleep 5

		# start client
		just start-etcd-bench-client {{warmup}} {{measurement}} localhost {{op}} {{mode}} "{{kv_range}}" {{block_size}}

		kill -KILL (jobs -p)
		sleep 10
	end

start-pb-bench-client warmup measurement node_name="localhost" op="write" mode="timed" kv_range="10000 20000" block_size="2000" :
	{{BIN_PATH}} benchmark-client --mode {{mode}} --op-type {{op}} --block-size {{block_size}} --kv-range {{kv_range}} --warmup {{warmup}} --measurement {{measurement}} --name client1 --node {{node_name}}:8010

start-etcd-bench-client warmup measurement node_name="localhost" op="write" mode="timed" kv_range="10000 20000" block_size="2000":
	{{BIN_PATH}} etcd-benchmark --mode {{mode}} --warmup {{warmup}} --measurement {{measurement}} --op-type {{op}} --block-size {{block_size}} --kv-range {{kv_range}} --name client1 --endpoints http://{{node_name}}:8010

all-benchmarks-local iterations="2" warmup="10" measurement="30" mode="timed" kv_range="10000 20000" block_size="2000":
	#!/usr/bin/env fish
	just prdt-benchmark-local {{iterations}} {{warmup}} {{measurement}} read {{mode}} '{{kv_range}}' {{block_size}}
	just prdt-benchmark-local {{iterations}} {{warmup}} {{measurement}} write {{mode}} '{{kv_range}}' {{block_size}}
	just prdt-benchmark-local {{iterations}} {{warmup}} {{measurement}} mixed {{mode}} '{{kv_range}}' {{block_size}}
	just etcd-benchmark-local {{iterations}} {{warmup}} {{measurement}} read {{mode}} '{{kv_range}}' {{block_size}}
	just etcd-benchmark-local {{iterations}} {{warmup}} {{measurement}} write {{mode}} '{{kv_range}}' {{block_size}}
	just etcd-benchmark-local {{iterations}} {{warmup}} {{measurement}} mixed {{mode}} '{{kv_range}}' {{block_size}}

start-etc-node number="1" host1="localhost" host2="localhost" host3="localhost":
	etcd --data-dir=/tmp/data1.etcd --name machine-{{number}} --initial-advertise-peer-urls http://localhost:238{{number}} --listen-peer-urls http://localhost:238{{number}} --advertise-client-urls http://localhost:80{{number}}0 --listen-client-urls http://localhost:80{{number}}0 --initial-cluster machine-1=http://localhost:2381,machine-2=http://localhost:2382,machine-3=http://localhost:2383 --initial-cluster-state new --initial-cluster-token token-01

etc-client:
	{{BIN_PATH}} etcd-client --endpoints http://localhost:8010

prdt-client:
	{{BIN_PATH}} client --endpoints http://localhost:8010