FROM docker.io/sbtscala/scala-sbt:eclipse-temurin-21.0.7_6_1.11.2_3.7.1

WORKDIR /src
COPY . .

RUN sbt proBench/Universal/packageBin

FROM openjdk:21-jdk-slim

RUN apt-get update -y
RUN apt-get install unzip

WORKDIR /project


COPY --from=0 ["/src/Modules/Protocol Benchmarks/target/universal/probench.zip", "."]
RUN unzip probench.zip
RUN rm probench.zip

ENTRYPOINT ["/probench/bin/probench"]
